import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import styled from 'styled-components'

import ResumeButton from '../comp/Resume'
import ProfilePicture from '../comp/ProfilePic'

const Par = styled.p`
  font-family: 'Heebo';
  font-size: 19px;
  margin-top: 30px;
  margin-bottom: 40px;
`

const Header = styled.p`
  font-size: 44px;
  font-family: 'Heebo';
  font-weight: 300;
  margin: 0px;
  padding: 0px;
`

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Raha's portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.ico" />
      </Head>

      <div className={styled.wrapper}>

        <div className={styles.section1}>
          <div className={styles.box1}>
            <Header>Hello! <span className={styles.name}>I am Raha!</span></Header>
            <span className={styles.name}>Front-end Developer</span>
            <Par>Front-end developer striving to join the ever-going technology industry with an active passion for web/app development. Strong problem-solving and leadership skills from participating in multiple team projects, volunteering, and freelance development.</Par>
            <ResumeButton />
          </div>

          <div className={styles.box2}>
            <ProfilePicture />
          </div>
        </div>
      </div>

    </div>
  )
}
