import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import styled from 'styled-components'

import ResumeButton from '../comp/Resume'
import ProfilePicture from '../comp/ProfilePic'
import TechnologyCard from '../comp/Technology'

const Par = styled.p`
  font-family: 'Heebo';
  font-size: 19px;
  margin-top: 30px;
  margin-bottom: 40px;
`

const Header = styled.p`
  font-size: 44px;
  font-family: 'Heebo';
  font-weight: 300;
  margin: 0px;
  padding: 0px;
`

const Box21 = styled.div`
  padding-top: 20px;
`

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Raha's portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.ico" />
      </Head>

      <div className={styled.wrapper}>

        <div className={styles.section1}>
          <div className={styles.box1}>
            <Header>Hello, <span className={styles.name}>I am Raha!🐢</span></Header>
            <span className={styles.name}>Front-end Developer</span>
            <Par>I'm striving to join the ever-groing technology industry with an active passion for web/app development. Strong problem-solving and leadership skills from participating in multiple team projects, volunteering, and freelance development.</Par>
            <ResumeButton />
          </div>

          <div className={styles.box2}>
            <ProfilePicture />
          </div>
        </div>

        <div className={styles.section2}>
          <Box21>
            <span className={styles.name}>My Toolkit👨‍💻</span>
          </Box21>

          <div className={styles.cards}>
            <TechnologyCard
              img="./js.png"
              title="JavaScript"
            />
            <TechnologyCard
              img="./react.png"
              title="React and React Native"
            />
            <TechnologyCard
              img="./next.png"
              title="Next.js"
            />
            <TechnologyCard
              img="./node.png"
              title="Node.js"
            />
            <TechnologyCard
              img="./git.png"
              title="Git"
            />
            <TechnologyCard
              img="./figma.png"
              title="Figma"
            />
            <TechnologyCard
              img="./styled.png"
              title="Styled-components"
            />
          </div>

        </div>
      </div>

    </div>
  )
}
